redis:
    image: redis
db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
vote:
    image: neha2602/vote-app
    ports:
       - 5000:80
    links:
       - redis:redis
result:
    image: neha2602/result-app
    ports:
       - 5001:80
    links:
       - redis:redis
       - db:db
worker:
    image: neha2602/worker-app
    links:
       - redis:redis
       - db:db
